### ISSUE TITLE
11代CPU  Not supported问题

### ISSUE THREAD

**Issue by di-photos** [zhtengw/unraid-i915-sriov#6]
大佬，unraid版本: 6.11.5，i5-11500安装插件后在设置中SR-IOV Status显示为Not supported，PCI 设备和 IOMMU 组中只显示一个显卡选项，请问需要怎么设置吗？
![image](https://user-images.githubusercontent.com/112997237/236360629-f8250259-0e14-4217-82d9-4e8ac1f675bb.png)
![image](https://user-images.githubusercontent.com/112997237/236360698-3f458087-1100-4686-86f8-4d2ba183aaa3.png)

**Comment by zhtengw** [comment]
插件提示Not Supported就表示这个核显不支持SR-IOV，设置不了。i5-11500是Rocket-Lake的CPU，不支持SR-IOV虚拟化技术。

**Comment by di-photos** [comment]
好的，谢谢大佬！！！
